version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d   # monta tus scripts SQL
      - db_data:/var/lib/postgresql/data       # persistencia de datos
    networks:
      - backend

  autenticacion:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: autenticacion
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_R2DBC_URL: r2dbc:postgresql://postgres:5432/postgres
      SPRING_R2DBC_USERNAME: postgres
      SPRING_R2DBC_PASSWORD: 123456
      SECURITY_JWT_SECRET: 1a2b3c4d5e6f7g8h9i0j1k2l3m4n5o6p7q8r9s0t1u2v3w4x5y6z7a8b9c0d1e2f
      # Override application.yaml adapters.r2dbc.* to reach the postgres service
      #ADAPTERS_R2DBC_HOST: postgres
      #ADAPTERS_R2DBC_PORT: "5432"
      #ADAPTERS_R2DBC_DATABASE: postgres
      #ADAPTERS_R2DBC_SCHEMA: public
      #ADAPTERS_R2DBC_USERNAME: postgres
      #ADAPTERS_R2DBC_PASSWORD: 123456
    ports:
      - "8080:8080"
    networks:
      - backend

  solicitudes:
    build: # <--- Use 'build' instead of 'image'
      context: C:\workspace_virfelo1\RetoTecnico\SOLICITUDES\ # <--- Set the context to where your Dockerfile is located
      dockerfile: Dockerfile # <--- Specify the path to your Dockerfile
    container_name: solicitudes
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_R2DBC_URL: r2dbc:postgresql://postgres:5432/postgres
      SPRING_R2DBC_USERNAME: postgres
      SPRING_R2DBC_PASSWORD: 123456
      SECURITY_JWT_SECRET: 1a2b3c4d5e6f7g8h9i0j1k2l3m4n5o6p7q8r9s0t1u2v3w4x5y6z7a8b9c0d1e2f
      #ADAPTERS_R2DBC_HOST: postgres
      #ADAPTERS_R2DBC_PORT: "5432"
      #ADAPTERS_R2DBC_DATABASE: postgres
      #ADAPTERS_R2DBC_SCHEMA: public
      #ADAPTERS_R2DBC_USERNAME: postgres
      #ADAPTERS_R2DBC_PASSWORD: 123456
      AUTH_SERVICE_URL: http://autenticacion:8080
    ports:
      - "8085:8085"
    networks:
      - backend

volumes:
  db_data:

networks:
  backend:
    driver: bridge



